// utils/classIcons.ts
// Map each BDO class name to its icon path in the public folder
// Replace the paths with your actual filenames once you add them to /public/icons/classes/

export const classIcons: Record<string, string> = {
  Warrior:      '/icons/classes/Warrior.png',
  Ranger:       '/icons/classes/Ranger.png',
  Sorceress:    '/icons/classes/Sorceress.png',
  Berserker:    '/icons/classes/Berserker.png',
  Tamer:        '/icons/classes/Tamer.png',
  Musa:         '/icons/classes/Musa.png',
  Maehwa:       '/icons/classes/Maehwa.png',
  Valkyrie:     '/icons/classes/Valkyrie.png',
  Kunoichi:     '/icons/classes/Kunoichi.png',
  Ninja:        '/icons/classes/Ninja.png',
  Wizard:       '/icons/classes/Wizard.png',
  Witch:        '/icons/classes/Witch.png',
  'Dark Knight': '/icons/classes/Dark_knight.png',
  Striker:      '/icons/classes/Striker.png',
  Mystic:       '/icons/classes/Mystic.png',
  Lahn:         '/icons/classes/Lahn.png',
  Shai:         '/icons/classes/Shai.png',
  Guardian:     '/icons/classes/Guardian.png',
  Hashashin:    '/icons/classes/Hashashin.png',
  Nova:         '/icons/classes/Nova.png',
  Sage:         '/icons/classes/Sage.png',
  Corsair:      '/icons/classes/Corsair.png',
  Drakania:     '/icons/classes/Drakania.png',
  Woosa:        '/icons/classes/Woosa.png',
  Maegu:        '/icons/classes/Maegu.png',
  Scholar:      '/icons/classes/Scholar.png',
  Dosa:         '/icons/classes/Dosa.png',
  Deadeye:      '/icons/classes/Deadeye.png',
  Wukong:       '/icons/classes/Wukong.png',
  Seraph:       '/icons/classes/Seraph.png',
  Archer:        '/icons/classes/Archer.png',
}